version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run: echo "Run Build"

  test:
    docker:
      - image: circleci/node:7.10
    steps:
      - run: echo "Run Test"
  
  deploy:
    docker:
      - image: circleci/node:7.10
    steps:
      - run: 
          name: "Setup custom environment variables"
          command: |
            echo 'export MY_ENV_VAR="Repo - ${CIRCLE_PROJECT_REPONAME}; SHA1 - ${CIRCLE_SHA1}; Branch - ${CIRCLE_BRANCH}; Build Num - ${CIRCLE_BUILD_NUM}; "' >> $BASH_ENV
      - run:
          name: ${MY_ENV_VAR}
          command: echo ${CIRCLE_BRANCH}
      - run:
          name: "What was my custom environment variable?"
          command: echo ${MY_ENV_VAR}

workflows:
  version: 2
  # build_and_test:
  #   jobs:
  #     - build
  #     - test:
  #         requires: 
  #           - build

  deploy_prod:
    jobs:
     - deploy
        # filters:
        #   branches:
        #     ignore: /.*/
        #   tags:
        #     only: /^\d+\.\d+\.\d+$/

        

# version: 2
# jobs:
#   build:
#     docker:
#       - image: circleci/node:7.10
#     steps:
#       - checkout
#       - restore_cache:
#         - run: echo "Build Test"

#   deploy: 
#     filters:
#       tags:
#         only: /^\d+\.\d+\.\d+$/
#     steps:
#       - run: echo "Deploy Test"

# workflows:
#   version: 2
#   CircleCITest_build:
#     jobs:
#       - build
  # CircleCITest_deploy:
  #   filters:
  #     branches:
  #       ignore: /.*/
  #     tags:
  #       only: /^\d+\.\d+\.\d+$/
  #   jobs:
  #      - deploy
