version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run: echo "Run Build"

  test:
    docker:
      - image: circleci/node:7.10
    requires: 
      - build
    steps:
      - run: echo "Run Test"
  
  deploy:
    docker:
      - image: circleci/node:7.10
    requires: 
      - test
    steps:
      - run: echo "Run Deploy"

workflows:
  version: 2
  build_and_test:
    jobs:
      - deploy
        

# version: 2
# jobs:
#   build:
#     docker:
#       - image: circleci/node:7.10
#     steps:
#       - checkout
#       - restore_cache:
#         - run: echo "Build Test"

#   deploy: 
#     filters:
#       tags:
#         only: /^\d+\.\d+\.\d+$/
#     steps:
#       - run: echo "Deploy Test"

# workflows:
#   version: 2
#   CircleCITest_build:
#     jobs:
#       - build
  # CircleCITest_deploy:
  #   filters:
  #     branches:
  #       ignore: /.*/
  #     tags:
  #       only: /^\d+\.\d+\.\d+$/
  #   jobs:
  #      - deploy
