version: 2.1
orbs:
  slack: circleci/slack@3.4.0

jobs:
  build:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run: echo "Run Build"

  test:
    docker:
      - image: circleci/node:7.10
    steps:
      - run: 
          name: "Setup custom environment variables"
          command: |
            echo 'export DEPLOYMENT_BUNDLE_NAME="${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BRANCH}.${CIRCLE_BUILD_NUM}.${CIRCLE_SHA1}.tar.gz"' >> $BASH_ENV
      - slack/notify:
          channel: 'returns-deployment'
          color: '#8A9B0F'
          title: ':package: Returns Front End deployment package created - #${CIRCLE_BUILD_NUM}'
          title_link: '${CIRCLE_COMPARE_URL}'
          message: '*Repo:* \`${CIRCLE_PROJECT_REPONAME}\` - *Branch:* \`${CIRCLE_BRANCH}\` - *Initiator:* \`${CIRCLE_USERNAME}\`'
          footer: 'To deploy: \`git tag ${CIRCLE_SHA1} <environment>\`'
          webhook: '${SLACK_WEBHOOK}'
          include_project_field: false
          include_job_number_field: false


  retrieve_package:
    docker:
      - image: circleci/node:7.10
    steps:
      - run: echo "Run Retrieve"
  
  qa_deploy:
    docker:
      - image: circleci/node:7.10
    steps:
      - slack/notify:
          channel: 'returns-deployment'
          color: '#F8CA00'
          title: 'Returns Front End QA deployment deployment started.'
          message: '*Initiator:* ${CIRCLE_USERNAME} - *Tag:* ${CIRCLE_TAG}'
          webhook: '${SLACK_WEBHOOK}'
          include_project_field: false
          include_job_number_field: false
      - run: 
          name: "Setup custom QA environment variables"
          command: |
            echo 'export DEPLOYMENT_BUNDLE_NAME="${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BRANCH}.${CIRCLE_BUILD_NUM}.${CIRCLE_SHA1}.zip"' >> $BASH_ENV
      - run:
          name: "My Deployment QA Output"
          command: echo ${CIRCLE_BRANCH}
      - run:
          name: "Deployment Bundle"
          command: echo ${DEPLOYMENT_BUNDLE_NAME}
      - slack/notify:
          channel: 'returns-deployment'
          color: '#F8CA00'
          title: 'Returns Front End QA deployment complete'
          message: '*Initiator:* ${CIRCLE_USERNAME} - *Tag:* ${CIRCLE_TAG}'
          footer: 'Not really...  this is just a workflow test.'
          webhook: '${SLACK_WEBHOOK}'
          include_project_field: false
          include_job_number_field: false

  stage_deploy:
    docker:
      - image: circleci/node:7.10
    steps:
      - slack/notify:
          channel: 'returns-deployment'
          color: '#E97F02'
          title: 'Returns Front End STAGING deployment has been approved - Starting deployment.'
          message: '*Initiator:* ${CIRCLE_USERNAME} - *Tag:* ${CIRCLE_TAG}'
          webhook: '${SLACK_WEBHOOK}'
          include_project_field: false
          include_job_number_field: false
      - run: 
          name: "Setup custom environment variables"
          command: |
            echo 'export DEPLOYMENT_BUNDLE_NAME="${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BRANCH}.${CIRCLE_BUILD_NUM}.${CIRCLE_SHA1}.zip"' >> $BASH_ENV
      - run:
          name: "My Deployment Output"
          command: echo ${CIRCLE_BRANCH}
      - run:
          name: "Deployment Bundle"
          command: echo ${DEPLOYMENT_BUNDLE_NAME}
      - slack/notify:
          channel: 'returns-deployment'
          color: '#E97F02'
          title: 'Returns Front End STAGING deployment complete'
          message: '*Initiator:* ${CIRCLE_USERNAME} - *Tag:* ${CIRCLE_TAG}'
          footer: 'Not really...  this is just a workflow test.'
          webhook: '${SLACK_WEBHOOK}'
          include_project_field: false
          include_job_number_field: false

  prod_deploy:
    docker:
      - image: circleci/node:7.10
    steps:
      - slack/notify:
          channel: 'returns-deployment'
          color: '#BD1550'
          title: 'Returns Front End PRODUCTION deployment has been approved - Starting deployment.'
          message: '*Initiator:* ${CIRCLE_USERNAME} - *Tag:* ${CIRCLE_TAG}'
          webhook: '${SLACK_WEBHOOK}'
          include_project_field: false
          include_job_number_field: false
      - run: 
          name: "Setup custom environment variables"
          command: |
            echo 'export DEPLOYMENT_BUNDLE_NAME="${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BRANCH}.${CIRCLE_BUILD_NUM}.${CIRCLE_SHA1}.zip"' >> $BASH_ENV
      - run:
          name: "My Deployment Output"
          command: echo ${CIRCLE_BRANCH}
      - run:
          name: "Deployment Bundle"
          command: echo ${DEPLOYMENT_BUNDLE_NAME}
      - slack/notify:
          channel: 'returns-deployment'
          color: '#BD1550'
          title: 'Returns Front End PRODUCTION deployment complete'
          message: '*Initiator:* ${CIRCLE_USERNAME} - *Tag:* ${CIRCLE_TAG}'
          footer: 'Not really...  this is just a workflow test.'
          webhook: '${SLACK_WEBHOOK}'
          include_project_field: false
          include_job_number_field: false
      
workflows:
  version: 2
  CircleCITest_CI_Build:
    jobs:
      - build
      - test:
          requires: 
            - build

  CircleCITest_Deploy_Prod:
    jobs:
      - hold:
          type: approval
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^production-.*$/
      - slack/approval-notification:
          message: 'APPROVAL REQUIRED - Returns Front End deployment initiated to PRODUCTION by ${CIRCLE_USERNAME}'
          url: 'https://circleci.com/workflow-run/${CIRCLE_WORKFLOW_ID}'
          color: "#BD1550"
          webhook: '${SLACK_WEBHOOK}'
          include_project_field: false
          include_job_number_field: false
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^production-.*$/
      - prod_deploy:
          requires:
            - hold
            - slack/approval-notification
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^production-.*$/
      
  CircleCITest_Deploy_Stage:
    jobs:
      - hold:
          type: approval
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^stage-.*$/
      - slack/approval-notification:
          message: 'APPROVAL REQUIRED - Returns Front End deployment initiated to STAGING by ${CIRCLE_USERNAME}'
          url: 'https://circleci.com/workflow-run/${CIRCLE_WORKFLOW_ID}'
          color: "#E97F02"
          webhook: '${SLACK_WEBHOOK}'
          include_project_field: false
          include_job_number_field: false
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^stage-.*$/
      - stage_deploy:
          requires:
            - hold
            - slack/approval-notification
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^stage-.*$/

  CircleCITest_Deploy_QA:
    jobs:
      - qa_deploy:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^(qa01|qa02)-.*$/
