version: 2.1
orbs:
  slack: circleci/slack@3.4.0

jobs:
  build:
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run: echo "Run Build"

  test:
    docker:
      - image: circleci/node:7.10
    steps:
      - run: echo "Run Test"
      - slack/notify:
          channel: 'returns-deployment'
          color: '#42e2f4'
          message: 'Build package created. To deploy type git tag CIRCLE_SHA1 environment'
          webhook: 'https://hooks.slack.com/services/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'

  retrieve_package:
    docker:
      - image: circleci/node:7.10
    steps:
      - run: echo "Run Retrieve"
  
  deploy:
    docker:
      - image: circleci/node:7.10
    steps:
      - run: 
          name: "Setup custom environment variables"
          command: |
            echo 'export DEPLOYMENT_BUNDLE_NAME="${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BRANCH}.${CIRCLE_BUILD_NUM}.${CIRCLE_SHA1}.zip"' >> $BASH_ENV
      - run:
          name: "My Deployment Output"
          command: echo ${CIRCLE_BRANCH}
      - run:
          name: "Deployment Bundle"
          command: echo ${DEPLOYMENT_BUNDLE_NAME}
      
workflows:
  version: 2
  CircleCITest_CI_Build:
    jobs:
      - build
      - test:
          requires: 
            - build

  CircleCITest_Deploy_Prod:
    jobs:
      - deploy:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^production$/

  CircleCITest_Deploy_Stage:
    jobs:
      - deploy:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^stage$/

  CircleCITest_Deploy_QA:
    jobs:
      - deploy:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^(qa01|qa02)$/

  

        

# version: 2
# jobs:
#   build:
#     docker:
#       - image: circleci/node:7.10
#     steps:
#       - checkout
#       - restore_cache:
#         - run: echo "Build Test"

#   deploy: 
#     filters:
#       tags:
#         only: /^\d+\.\d+\.\d+$/
#     steps:
#       - run: echo "Deploy Test"

# workflows:
#   version: 2
#   CircleCITest_build:
#     jobs:
#       - build
  # CircleCITest_deploy:
  #   filters:
  #     branches:
  #       ignore: /.*/
  #     tags:
  #       only: /^\d+\.\d+\.\d+$/
  #   jobs:
  #      - deploy
